# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccaedffb97b9d2d90c4b492660b7a64983de2efff2b21ab72042760385d6b627e15a0462d1436041e47e97664513c54169a47734a9bbb48a155de15a70de6033

test:
  secret_key_base: 1b3db41cb9c4b12e46ed300cf69111d7e8a704a90a9dd25c94403840b195ca6ce7a231d40f1674940f3740bf27281aa402ec63d420b86c55b70d38dc07a6ada6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
